version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:8000:8000
    expose:
      - 8000
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
      MYSQL_ROOT_PASSWORD: laravel
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
